"""empty message

Revision ID: 2c2c7b5a3b8e
Revises: 
Create Date: 2021-03-26 16:50:51.629388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2c7b5a3b8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('us_generation_power')
    op.drop_table('us_percentage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('us_percentage',
    sa.Column('State', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Nuclear', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Coal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Natural Gas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Petroleum', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Hydro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Geothermal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Solar - PV', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Wind', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Biomass and Other', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('us_generation_power',
    sa.Column('YEAR', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('STATE', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('TYPE OF PRODUCER', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ENERGY SOURCE', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('GENERATION Mwh', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
